### ISSUE TITLE
ReferenceError: 'Symbol' is undefined

### ISSUE THREAD

**Issue by m1ch4ls** [ufal/perl-pmltq-web#48]
IE 10, 11 bug.

I can't get a better stacktrace, but this at least shows that it's something related to tokenizer.

```
ReferenceError: 'Symbol' is undefined
   at addNewRule (https://lindat.mff.cuni.cz/services/pmltq/a6f9ef0f73ad0eb997df-pmltq.js:85:31984)
   at u (https://lindat.mff.cuni.cz/services/pmltq/a6f9ef0f73ad0eb997df-pmltq.js:86:10030)
   at Anonymous function (https://lindat.mff.cuni.cz/services/pmltq/a6f9ef0f73ad0eb997df-pmltq.js:86:10434)
   at tt (https://lindat.mff.cuni.cz/services/pmltq/a6f9ef0f73ad0eb997df-pmltq.js:1:4280)
   at Anonymous function (https://lindat.mff.cuni.cz/services/pmltq/a6f9ef0f73ad0eb997df-pmltq.js:1:15114)
   at t (https://lindat.mff.cuni.cz/services/pmltq/a6f9ef0f73ad0eb997df-pmltq.js:86:10395)
   at link (https://lindat.mff.cuni.cz/services/pmltq/a6f9ef0f73ad0eb997df-pmltq.js:86:8191)
   at Anonymous function (https://lindat.mff.cuni.cz/services/pmltq/a6f9ef0f73ad0eb997df-pmltq.js:81:5317)
   at re (https://lindat.mff.cuni.cz/services/pmltq/a6f9ef0f73ad0eb997df-pmltq.js:81:5383)
   at m (https://lindat.mff.cuni.cz/services/pmltq/a6f9ef0f73ad0eb997df-pmltq.js:80:31377) <div class="code-listing ng-pristine ng-untouched ng-valid ng-isolate-scope" ng-model="query" query-highlighter="treebank">
```

**Comment by m1ch4ls** [comment]
Fixed in caf229d0d35aa668f8cb1b1963415617205b9ab3
